# Seed box login name
    seedbox_login: "username"
# seedbox password
    seedbox_pw: "password"
# seedbox address
    seedbox_addr: "XXXX@seedbox.io"
# directory for managing torrents
    torrent_dir: "/place/to/where/torrent/files/should/go"
# place where .torrent files land (likely your DL folder)
    target_dir: "~/Downloads/"
# place where the local downloads get categorized and sorted.
    download_dir: "~/Downloads/torrents"
# place where the finished torrents go in the seedbox directory
# this needs to be configured manually in RuTorrent.
    ftp_remote_directory_for_completed_downloads: "/files/Completed Downloads/"
# put the name of the "watch" folder here. this is folder that auto downloads torrents it finds in here.
    ftp_remote_watch_directory: "/watch"
# places on your local computer you want to check against to see if torrent files are already downloaded.
# you can add as many as you like.
    file_directories:
        - "~/Music"
        - "~/Videos"
