# Seed box login name
    seedbox_login: "username"
# seedbox password
    seedbox_pw: "password"
# seedbox address
    seedbox_addr: "XXXX@seedbox.io"
# directory for managing torrents
    torrent_dir: "/place/to/where/torrent/files/should/go"
# place where .torrent files land (likely your DL folder)
    target_dir: "/downloads/"
# place where the finished torrents go in the seedbox directory
# this needs to be configured manually in RuTorrent.
    ftp_remote_directory_for_completed_downloads: "/files/Completed Downloads/"
